### ISSUE TITLE
imgSrcToDataURL returns [object Object] not string

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolanlawson/blob-util#13]
Hello Support,

The code below returns an Object not a string. Can you advise?.

```
var myBlob = blobUtil.imgSrcToDataURL('http://my-personaltrainer.nl/images/image.png', 'image/jpeg');
console.log("myBlob = " + myBlob);
```
Kind regards,
Mario

**Comment by nolanlawson** [comment]
Hi, the Object you are seeing is a promise, so you need to use the promise style as specified in the API.
