### ISSUE TITLE
imgSrcToDataURL in android 4.2 get nothing

### ISSUE THREAD

**Issue by yesir1006** [nolanlawson/blob-util#14]
hi, 

I use imgSrcToDataURL to convert url (get from cordova image picker/camera plugin) to dataURL, in Android 4.2 image cannot show, while in Android 5.0 everything works fine. Any idea on this? Thanks!

**Comment by yesir1006** [comment]
sorry, my fault, no business with imgSrcToDataURL, it seems that there's some different on image format between android 4.2(png) and android 5, still working on it. Thanks.

**Comment by nolanlawson** [comment]
Thanks, no prob
