### ISSUE TITLE
Author/copyright/license info in dist/*.js

### ISSUE THREAD

**Issue by brodybits** [nolanlawson/blob-util#20]
I needed to use your wonderful blob-util in a project for a client. When I add blob-util.min.js to the project there is no trace of author or license info so I had to add a new section it its README.txt file with the copyright/license info which the client will hopefully actually read, someday.

It would be much better to have this info in dist/blob-util*.js so it doesn't get lost or forgotten. For example:
- https://github.com/MrRio/jsPDF/blob/master/dist/jspdf.min.js
- https://github.com/macek/jquery-serialize-object/blob/master/dist/jquery.serialize-object.min.js

Off-topic: +1 for publishing dist/blob-util.js as well as dist/blob-util.min.js

**Comment by nolanlawson** [comment]
Thanks for the vote of confidence! :) I have to admit, though, that I am starting to move away from prebuilt distributions (e.g. `dist` and Bower) in favor of npm. That way, the LICENSE is automatically included in the npm-distributed tarball, and I'm sure you could write a Browserify transform or Webpack loader that copies the license information to the built JS file if you really need to. (Or just commit the node_modules to source, or `cat node_modules/*/LICENSE*` or whatever you need to do.)

So at some point, even for this library, I will probably just remove the `dist`s and ask people to either build it themselves, or use something like https://wzrd.in/. TBH, it's just too much effort to maintain several different bundle formats, and I don't think it should be library authors' responsibility to cater to every user's precise use case. Thanks for understanding.
