### ISSUE TITLE
Use native promises

### ISSUE THREAD

**Issue by selbekk** [nolanlawson/blob-util#21]
Instead of using the `pouchdb-promise` lib (that uses `bluebird`), why not just use native promises? Most projects these days use transpilers and polyfills, and therefore have this in place already.

**Comment by nolanlawson** [comment]
`pouchdb-promise` actually uses native promises if they're available. In the browser it uses `lie`, and in Node it uses `bluebird`: https://github.com/calvinmetcalf/pouchdb-promise/blob/d8f4af2cd7abc88088ea0912437a0289e216f4b2/index.js#L1

**Comment by nolanlawson** [comment]
`lie` switch: https://github.com/calvinmetcalf/pouchdb-promise/blob/d8f4af2cd7abc88088ea0912437a0289e216f4b2/package.json#L11

**Comment by selbekk** [comment]
Ah okay :+1:
