### ISSUE TITLE
Warning while bundling (in Webpack)

### ISSUE THREAD

**Issue by selbekk** [nolanlawson/blob-util#22]
When bundling this dependency, I get the following warning:

```
WARNING in ./~/lie/dist/lie.js
Critical dependencies:
1:407-414 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/lie/dist/lie.js 1:407-414
```

A minor annoyance. Possible to fix somehow?

**Comment by nolanlawson** [comment]
It's because `pouchdb-promise` is using an outdated version of `lie`. Probably I could just do the `lie`/native Promise switch myself.

**Comment by nolanlawson** [comment]
should be fixed now

**Comment by selbekk** [comment]
Great, works a treat :+1: Thanks for fixing this!
