### ISSUE TITLE
help with react-native error

### ISSUE THREAD

**Issue by npomfret** [nolanlawson/blob-util#24]
I'm trying to use blob-util in a react native app on ios.  I keep getting this error but can't figure out what to do 

> you're probably in an ios webworker. please include use beatgammit's base64-js

**Comment by nolanlawson** [comment]
Sorry, I'm really not familiar enough with React Native to understand what's going on here. Probably it's because `window.atob` and `window.btoa` don't exist in React Native.

**Comment by npomfret** [comment]
Thanks anyway.  I just don't think it's possible at the moment.
