### ISSUE TITLE
TypeError: Blob is not a constructor when using in nodejs

### ISSUE THREAD

**Issue by josephrocca** [nolanlawson/blob-util#27]
I tried to use this in nodejs and on line 93 of index.js I'm getting `TypeError: Blob is not a constructor`.

![image](https://cloud.githubusercontent.com/assets/1167575/24835831/21229e7e-1d3f-11e7-8810-5feb538bebc1.png)

Given that quite a few people seem to be using this, I was surprised and thought it might be something I was doing wrong. I cut it down to this minimal example, and I still get the error (coming from `blobUtil.createBlob`):

```javascript
let blobUtil = require('blob-util');
let myString = "blah blah";
let myBlob = blobUtil.createBlob([myString]);
let myUrl = blobUtil.createObjectURL(myBlob, { type: 'application/javascript; charset=utf-8' });
console.log(myUrl);
```

**Comment by eapostol** [comment]
+1, although I had it originally working . I am using it in a react-native project.

**Comment by nolanlawson** [comment]
`Blob`s are a browser feature and are not supported in NodeJS or react-native: https://developer.mozilla.org/en-US/docs/Web/API/Blob
