### ISSUE TITLE
Unnecessary conversion for blobToArrayBuffer

### ISSUE THREAD

**Issue by sheerun** [nolanlawson/blob-util#3]
Hello. Thanks for creating this library!

I'd like to use it, but one thing bothers me: why in blobToArrayBuffer you first convert blobToBinaryString and then binaryStringToArrayBuffer?

FileReader can always readAsArrayBuffer, so you don't need to even allocate binary string representation.

Am I missing something?

**Comment by nolanlawson** [comment]
Fixed as of v1.1.2
