### ISSUE TITLE
blobToDataURL does not work in IE10

### ISSUE THREAD

**Issue by mchakraborty-pmap** [nolanlawson/blob-util#41]
The function **blobToDataURL** returns _null_ for the **dataURL** in IE 10.

As IE10 does not support the use of createObjectURL(), I wanted to use your library. I need an URL that can be added to the src attribute of an img.

**Comment by nolanlawson** [comment]
The tests are passing in Sauce Labs on IE 10, and [there is a test for blobToDataURL](https://github.com/nolanlawson/blob-util/blob/ca23a26a05f049eeaeda8d413320feb94c0c062f/test/test.js#L106-L111).

Closing old issues, please reopen especially if there's a reproducible test case, thanks.
