### ISSUE TITLE
can not find name 'blobUtil'

### ISSUE THREAD

**Issue by binita12345** [nolanlawson/blob-util#52]
when i use this node modules to convert my image in blob, i getting error **"can not find module 'blobUtil'"**. 

1. I have installed **"npm i blob-util"** module
2. import { canvasToBlob } from 'blob-util' , when i use to convert in blob in my app.
3. my code is: 
    blobUtil.imgSrcToBlob(res.json().data.productImage).then(function (blob) {
            // success
          }).catch(function (err) {
            // error
          });

How to solve this error or how to install or use modules in ionic 3 app.
please reply asap

**Comment by nolanlawson** [comment]
When you import using the ESM module format:

```js
import { canvasToBlob } from 'blob-util'
```

Then you omit the `blobUtil` part when you call it. It's only when you include it as a script tag that it creates a global `blobUtil` object. Hope that helps!

**Comment by binita12345** [comment]
Property 'imgSrcToDataURL' does not exist on type '{}'.
