### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by Aleksey-Danchin** [nolanlawson/blob-util#57]
Hi. In nodejs project add `blob-util` through `:~$ npm install blob-util --save`. ES6 module work, `import` finds module, it's ok. But `blobUtil` is `undefined`.

```javascript
import blobUtil from 'blob-util'
console.log(blobUtil) // undefined
````

**Comment by nolanlawson** [comment]
How are you using ES6 imports? Babel, `esm`, Webpack, `--experimental-modules`, something else? Node doesn't natively support ES6 modules. Also blob-util does not support Node, only the browser. :)

**Comment by nolanlawson** [comment]
You might also try `import * as blobUtil from 'blob-util'`.

**Comment by nolanlawson** [comment]
I updated the installation instructions after playing around with TypeScript and esm. https://github.com/nolanlawson/blob-util#install I'm pretty sure you want to use `import * as blobUtil`, please reopen if I'm wrong.
