### ISSUE TITLE
use chrome error

### ISSUE THREAD

**Issue by liuzhengming** [nolanlawson/blob-util#6]
`var blobURL = blobUtil.blobToBase64String(abc);`

> Uncaught (in promise) TypeError: Failed to execute 'readAsBinaryString' on 'FileReader': parameter 1 is not of type 'Blob'. {stack: (...), message: "Failed to execute 'readAsBinaryString' on 'FileReader': parameter 1 is not of type 'Blob'."}(anonymous function) @ blob-util.js:138blobToBinaryString @ blob-util.js:126blobToBase64String @ blob-util.js:176$scope.initizlie.then.$scope.readIdCard @ home.js:94(anonymous function) @ tray.js:21$get.Scope.$eval @ angular.js:14466$get.Scope.$apply @ angular.js:14565Tray.on.f @ tray.js:20(anonymous function) @ tray.js:10trigger @ tray.js:9(anonymous function) @ tray.js:229

**Comment by nolanlawson** [comment]
Is `abc` a Blob? It works for me in Chrome:

![screenshot 2015-04-23 08 05 28](https://cloud.githubusercontent.com/assets/283842/7296655/88c408c8-e98f-11e4-8cc1-507a775b6d2d.png)
