### ISSUE TITLE
ReferenceError: Blob is not defined

### ISSUE THREAD

**Issue by BernardoOlisan** [nolanlawson/blob-util#64]
I'm coding in nodejs using base64StringToBlob and it outputs this error `ReferenceError: Blob is not defined`
any idea?
![image](https://user-images.githubusercontent.com/46250121/175097642-b0de18c0-b410-457f-adf8-8edfb5beccb2.png)

**Comment by nolanlawson** [comment]
blob-util was designed for the browser, but Node is adding support for Blob in v15.7. https://developer.mozilla.org/en-US/docs/Web/API/Blob#browser_compatibility Hope that helps!
